#
# Highly recommend that you do NOT edit this file. Create your own my_app_steps.rb file and/or
# my_core_steps.rb files under features/step_definitions, and override these steps if required.
# If you create steps that you think belong here, feel free to open up a pull request on test_sweet.
#
Given(/^I wait for (\d+) seconds$/) do |seconds|
  sleep seconds.to_i
end

When(/^I touch at position (\d+),(\d+)$/) do |x, y|
  Appium::TouchAction.new.press(x: x, y: y, fingers: 1, tapCount: 1, duration: 0.5).perform
end

When(/^I touch "([^"]*)"$/) do |view_name|
  find_element(:name, view_name).click
end
